name: Build PDF
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    container: aergus/latex
    steps:
      - uses: actions/checkout@v3
      - run: latexmk -pdf MScThesis.tex
      - uses: actions/upload-artifact@v3
        with:
          name: print
          path: MScThesis.pdf
