name: Build PDF
on: [push]

jobs:
  Build:
    runs-on: ubuntu-latest
    container: aergus/latex
    steps:
      - uses: actions/checkout@v3
      - run: cd tex; latexmk -pdf -outdir=../out -jobname=BScThesis main
      - uses: actions/upload-artifact@v3
        with:
          name: print
          path: out/BScThesis.pdf
